In [1]:
from ib_insync import *
util.startLoop()

from trading_assignment import DeltaHedgeAlgo, VIXFuturesHedgeAlgo, PairsTradingAlgo

### TA1 Delta Hedge

In [2]:
# initialize the delta hedge algorithm
DeltaHedge = DeltaHedgeAlgo("SPY", client_id=1)
DeltaHedge.positions

[Position(account='DU6066633', contract=Stock(conId=756733, symbol='SPY', exchange='ARCA', currency='USD', localSymbol='SPY', tradingClass='SPY'), position=58.0, avgCost=377.19),
 Position(account='DU6066633', contract=Option(conId=564970818, symbol='SPY', lastTradeDateOrContractMonth='20221021', strike=390.0, right='C', multiplier='100', currency='USD', localSymbol='SPY   221021C00390000', tradingClass='SPY'), position=-10.0, avgCost=1255.26991)]

In [3]:
# rebalance and print positions 
pos = DeltaHedge.rebalance()
[p for p in pos if p.contract.symbol == "SPY"]

[Position(account='DU6066633', contract=Stock(conId=756733, symbol='SPY', exchange='ARCA', currency='USD', localSymbol='SPY', tradingClass='SPY'), position=71.0, avgCost=374.5588732394366),
 Position(account='DU6066633', contract=Option(conId=564970818, symbol='SPY', lastTradeDateOrContractMonth='20221021', strike=390.0, right='C', multiplier='100', exchange='SMART', currency='USD', localSymbol='SPY   221021C00390000', tradingClass='SPY'), position=-10.0, avgCost=1255.26991)]

In [4]:
# cleanup
DeltaHedge.ibconn.disconnect()

### TA2 VIX Futures Hedge

In [5]:
# initialize vix futures algorithm
vixf_date, esf_date = "20221116", "20221216"
VIXHedge = VIXFuturesHedgeAlgo(vixf_date, esf_date, client_id=2)

In [6]:
# exit any valid positions
VIXHedge.exit_positions()

No positions to exit.

In [7]:
# attempt to enter the VIX futures position
VIXHedge.enter_positions(10)

Signal is -0.04222766217870255 and daily roll is -2.61615903264042e-10. No action taken.

In [8]:
# cleanup
VIXHedge.ibconn.disconnect()

### TA3 Pairs Trading

In [9]:
# initiate a new pairs trading algorithm instance, print pairs data
PairsTrade = PairsTradingAlgo(client_id=3)
PairsTrade.data

Pairs data found in csv file.

               pair  hedge_ratio  spread_mean  spread_std
0    ('BAC', 'STT')     0.835780    -0.000180    0.025364
1   ('MMM', 'ALLE')     1.059201    -0.000058    0.035957
2    ('AME', 'APH')     1.124370     0.000275    0.033541
3   ('CARR', 'FRC')     0.737416    -0.000795    0.050381
4    ('ADI', 'TMO')     0.800082    -0.000036    0.035627
5   ('AMGN', 'WEC')     1.187299     0.000121    0.037344
6    ('BDX', 'PEG')     1.319306     0.000434    0.043917
7     ('ATO', 'ED')     1.041530     0.000268    0.030733
8    ('ADP', 'AJG')     1.057041     0.000098    0.038074
9    ('BAX', 'WBA')     1.132904     0.000615    0.049036
10   ('AWK', 'TXN')     0.978532     0.000093    0.040995
11  ('ANSS', 'BLK')     0.866572    -0.001062    0.064909
12    ('CB', 'TRV')     1.033365     0.000100    0.020935
13    ('AMP', 'RF')     1.822942     0.001442    0.070639
14   ('AIG', 'BSX')     1.080405     0.000147    0.044607
15   ('AXP', 'PRU')     1.097027     0.000029    0.035226
16  ('ADBE', 'KMX')     1.314480     0.001351    0.066315

In [11]:
# rebalance the pairs
PairsTrade.rebalance()

Zscore is -1.5548048967415233 - no action for ('BAC', 'STT') spread...
Can't find last price for one of ('MMM', 'ALLE'). Skipping.
Can't find last price for one of ('AME', 'APH'). Skipping.
Zscore is -0.502389963146997 - no action for ('CARR', 'FRC') spread...
Can't find last price for one of ('ADI', 'TMO'). Skipping.
Can't find last price for one of ('AMGN', 'WEC'). Skipping.
Zscore is 2.5248712719294635 - no action for ('BDX', 'PEG') spread...
Zscore is 1.2899934990204527 - shorting ('ATO', 'ED') spread with allocation of 222.0
Can't find last price for one of ('ADP', 'AJG'). Skipping.
Can't find last price for one of ('BAX', 'WBA'). Skipping.
Zscore is -1.7016756661313772 - no action for ('AWK', 'TXN') spread...
Zscore is -2.0535512761814694 - no action for ('ANSS', 'BLK') spread...
Zscore is -0.6323970358019126 - no action for ('CB', 'TRV') spread...
Zscore is 1.8126068742090662 - no action for ('AMP', 'RF') spread...
Zscore is -2.02104825117001 - no action for ('AIG', 'BSX') spread...
Zscore is -0.7602084002740551 - no action for ('AXP', 'PRU') spread...
Zscore is 2.9127024184077057 - no action for ('ADBE', 'KMX') spread...

In [12]:
# print positions
util.df(PairsTrade.ibconn.positions())

,account,contract,position,avgCost
0,DU6066633,"Stock(conId=273815, symbol='RF', exchange='NYS...",164.0,20.216098
1,DU6066633,"Stock(conId=5270, symbol='BSX', exchange='NYSE...",-543.0,39.673961
2,DU6066633,"Stock(conId=4886, symbol='BDX', exchange='NYSE...",-110.0,220.476639
3,DU6066633,"Stock(conId=178634687, symbol='WBA', exchange=...",505.0,31.925000
4,DU6066633,"Stock(conId=50530752, symbol='AWK', exchange='...",191.0,127.955236
5,DU6066633,"Stock(conId=12869, symbol='TMO', exchange='NYS...",-140.0,512.492419
6,DU6066633,"Stock(conId=2586156, symbol='KMX', exchange='N...",111.0,63.819009
7,DU6066633,"Stock(conId=61319701, symbol='AIG', exchange='...",502.0,48.801016
8,DU6066633,"Stock(conId=4661, symbol='ADP', exchange='NASD...",107.0,226.981963
9,DU6066633,"Stock(conId=756733, symbol='SPY', exchange='AR...",71.0,374.572958
10,DU6066633,"Stock(conId=35970258, symbol='AMP', exchange='...",-90.0,271.002552
11,DU6066633,"Stock(conId=9720, symbol='MMM', exchange='NYSE...",227.0,107.895000
12,DU6066633,"Stock(conId=198560237, symbol='WEC', exchange=...",124.0,86.298064
13,DU6066633,"Stock(conId=5049, symbol='BLK', exchange='NYSE...",-101.0,545.107287
14,DU6066633,"Stock(conId=4157, symbol='ADI', exchange='NASD...",174.0,140.505747
15,DU6066633,"Stock(conId=11005, symbol='PEG', exchange='NYS...",145.0,55.576897
16,DU6066633,"Stock(conId=4325, symbol='AJG', exchange='NYSE...",-114.0,176.037067
17,DU6066633,"Stock(conId=266145, symbol='AMGN', exchange='N...",-105.0,232.235028
18,DU6066633,"Stock(conId=138438437, symbol='ALLE', exchange...",-241.0,91.522774
19,DU6066633,"Stock(conId=13096, symbol='TXN', exchange='NAS...",-187.0,155.530960
20,DU6066633,"Stock(conId=4726368, symbol='ANSS', exchange='...",116.0,210.458621
21,DU6066633,"Stock(conId=265768, symbol='ADBE', exchange='N...",-85.0,284.811582
22,DU6066633,"Option(conId=564970818, symbol='SPY', lastTrad...",-10.0,1255.269910
23,DU6066633,"Stock(conId=8111188, symbol='BAX', exchange='N...",-446.0,54.903613
24,DU6066633,"Stock(conId=10098, symbol='BAC', exchange='NYS...",753.0,30.237032
25,DU6066633,"Stock(conId=2730980, symbol='STT', exchange='N...",-630.0,61.983450
26,DU6066633,"Stock(conId=4644, symbol='ATO', exchange='NYSE...",-222.0,102.502523
27,DU6066633,"Stock(conId=6691, symbol='ED', exchange='NYSE'...",231.0,81.905000

In [13]:
# cleanup
PairsTrade.ibconn.disconnect()